/*
 * Copyright 2010-2023 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.formver.core.conversion

import org.jetbrains.kotlin.contracts.description.*
import org.jetbrains.kotlin.fir.contracts.description.ConeContractConstantValues
import org.jetbrains.kotlin.fir.diagnostics.ConeDiagnostic
import org.jetbrains.kotlin.fir.symbols.FirBasedSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirFunctionSymbol
import org.jetbrains.kotlin.fir.types.ConeKotlinType
import org.jetbrains.kotlin.formver.core.effects
import org.jetbrains.kotlin.formver.core.embeddings.SourceRole
import org.jetbrains.kotlin.formver.core.embeddings.callables.NamedFunctionSignature
import org.jetbrains.kotlin.formver.core.embeddings.expression.*

/**
 * Carries the context needed while visiting a Kotlin contract description.
 *
 * @param returnVariable The Viper variable that will hold the function's return value,
 *   used to translate `returns(...)` effects into postcondition expressions.
 * @param functionContractOwner The FIR symbol of the function whose contract is being visited,
 *   used to look up value parameter symbols when resolving parameter references.
 */
data class ContractVisitorContext(
    val returnVariable: VariableEmbedding,
    // Kotlin function where the visited contract is attached to.
    val functionContractOwner: FirFunctionSymbol<*>,
)

/**
 * Converts Kotlin `contract { }` effect declarations into [ExpEmbedding]s that can be
 * used as Viper postconditions.
 *
 * Implements `KtContractDescriptionVisitor` — the Kotlin compiler's visitor interface for
 * the contract description AST (`KtEffectDeclaration` and its subtypes). Each `visitX`
 * method maps one contract node type to the corresponding Viper expression.
 *
 * `KtEffectDeclaration`s are nodes generated by the compiler, and as such have no source
 * information beyond the source of the `FirEffectDeclaration`. As such, we only assign
 * position information at the top level (in [getPostconditions]).
 *
 * @param ctx The program-level conversion context, used to embed types referenced in contracts.
 * @param signature The signature of the function being converted, used to resolve parameter
 *   references (formal params, dispatch/extension receivers) inside the contract.
 */
class ContractDescriptionConversionVisitor(
    private val ctx: ProgramConversionContext,
    private val signature: NamedFunctionSignature,
) : KtContractDescriptionVisitor<ExpEmbedding, ContractVisitorContext, ConeKotlinType, ConeDiagnostic>() {

    /**
     * Converts all effect declarations of [context]'s function into Viper postcondition
     * [ExpEmbedding]s, attaching source positions at the top level.
     *
     * Trivially-true conditions (`BooleanLit(true)`) are filtered out as they add no
     * information to the Viper verification.
     */
    fun getPostconditions(context: ContractVisitorContext): List<ExpEmbedding> =
        context.functionContractOwner.effects.map {
            it.effect.accept(this, context).withPosition(it.source)
        }.filter { it != BooleanLit(true) }

    /**
     * Converts a boolean constant reference (`true` / `false`) used inside a contract condition.
     * Any value other than the two known constants is an error.
     */
    override fun visitBooleanConstantDescriptor(
        booleanConstantDescriptor: KtBooleanConstantReference<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding = when (booleanConstantDescriptor) {
        ConeContractConstantValues.TRUE -> BooleanLit(true, SourceRole.Condition.Constant(true))
        ConeContractConstantValues.FALSE -> BooleanLit(false, SourceRole.Condition.Constant(false))
        else -> throw IllegalArgumentException("Unexpected boolean constant: $booleanConstantDescriptor")
    }

    /**
     * Converts a `returns(value)` effect declaration into a Viper expression about the return variable.
     *
     * Mapping:
     * - `returns()` (wildcard) → `true` (the effect holds unconditionally on any return).
     * - `returns(null)` → `returnVariable == null`.
     * - `returnsNotNull()` → `returnVariable != null`.
     * - `returns(true)` → `returnVariable == true`.
     * - `returns(false)` → `returnVariable == false`.
     *
     * NOTE: the compiler allows contracts like `returnsNotNull()` on functions with a non-nullable
     * return type without error. In that case, `returnsNotNull()` maps to `true` and `returns(null)`
     * maps to `false` to avoid a null comparison against a non-nullable value in Viper.
     */
    override fun visitReturnsEffectDeclaration(
        returnsEffect: KtReturnsEffectDeclaration<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding {
        return when (returnsEffect.value) {
            ConeContractConstantValues.WILDCARD -> BooleanLit(true, SourceRole.ReturnsEffect.Wildcard)
            /* NOTE: in a function that has a non-nullable return type, the compiler will not complain if there is an effect like
             * returnsNotNull(). So it is necessary to take care of these cases in order to avoid comparison between non-nullable
             * values and null. In a function that has a non-nullable return type, returnsNotNull() is mapped to true and returns(null)
             * is mapped to false
             */
            ConeContractConstantValues.NULL -> data.returnVariable.nullCmp(
                false,
                SourceRole.ReturnsEffect.Null(negated = false)
            )

            ConeContractConstantValues.NOT_NULL -> data.returnVariable.nullCmp(
                true,
                SourceRole.ReturnsEffect.Null(negated = true)
            )

            ConeContractConstantValues.TRUE -> EqCmp(
                data.returnVariable,
                BooleanLit(true),
                SourceRole.ReturnsEffect.Bool(true)
            )

            ConeContractConstantValues.FALSE -> EqCmp(
                data.returnVariable,
                BooleanLit(false),
                SourceRole.ReturnsEffect.Bool(false)
            )

            else -> throw IllegalArgumentException("Unexpected constant: ${returnsEffect.value}")
        }
    }

    /**
     * Converts a reference to a value parameter inside a contract into the corresponding
     * [VariableEmbedding] from the function signature, using [embeddedVar].
     */
    override fun visitValueParameterReference(
        valueParameterReference: KtValueParameterReference<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding = valueParameterReference.embeddedVar()

    /**
     * Converts an `isNull(x)` or `isNotNull(x)` predicate in a contract condition.
     *
     * Emits `x == null` or `x != null` respectively.
     *
     * NOTE: the compiler allows trivially-useless comparisons like `x != null` where `x` is
     * already non-nullable (with only a warning). These are handled gracefully: `x == null`
     * maps to `false` and `x != null` maps to `true` for non-nullable types, avoiding
     * ill-typed null comparisons in the generated Viper.
     */
    override fun visitIsNullPredicate(
        isNullPredicate: KtIsNullPredicate<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding {
        /* NOTE: useless comparisons like x != null with x non-nullable will compile with just a warning.
         * So it is necessary to take care of these cases in order to avoid comparison between non-nullable
         * values and null. Let x be a non-nullable variable, then x == null is mapped to false and x != null is mapped to true
         */
        val param = isNullPredicate.arg.embeddedVar()
        val role = SourceRole.Condition.IsNull(isNullPredicate.arg.getTargetParameter(data), isNullPredicate.isNegated)
        return param.nullCmp(isNullPredicate.isNegated, role)
    }

    /**
     * Converts a binary logic expression (`&&` or `||`) inside a contract condition.
     * Both sides are visited recursively. The resulting [SourceRole]s are combined into
     * a [SourceRole.Condition.Conjunction] or [SourceRole.Condition.Disjunction] for
     * traceability in error messages.
     */
    override fun visitLogicalBinaryOperationContractExpression(
        binaryLogicExpression: KtBinaryLogicExpression<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding {
        val left = binaryLogicExpression.left.accept(this, data)
        val right = binaryLogicExpression.right.accept(this, data)
        val lhsRole = left.sourceRole as SourceRole.Condition
        val rhsRole = right.sourceRole as SourceRole.Condition
        return when (binaryLogicExpression.kind) {
            LogicOperationKind.AND ->
                OperatorExpEmbeddings.And(left, right, SourceRole.Condition.Conjunction(lhsRole, rhsRole))

            LogicOperationKind.OR ->
                OperatorExpEmbeddings.Or(left, right, SourceRole.Condition.Disjunction(lhsRole, rhsRole))
        }
    }

    /**
     * Converts a logical negation (`!condition`) inside a contract.
     * Wraps the visited argument in [OperatorExpEmbeddings.Not] and records a
     * [SourceRole.Condition.Negation] for traceability.
     */
    override fun visitLogicalNot(
        logicalNot: KtLogicalNot<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding {
        val arg = logicalNot.arg.accept(this, data)
        return OperatorExpEmbeddings.Not(arg, SourceRole.Condition.Negation(arg.sourceRole as SourceRole.Condition))
    }

    /**
     * Converts a conditional effect (`returns(...) implies condition`) into a Viper implication.
     *
     * The effect (left-hand side) and condition (right-hand side) are both visited, then
     * combined as `effect ==> condition` using [OperatorExpEmbeddings.Implies]. The combined
     * [SourceRole.ConditionalEffect] is attached for error traceability.
     */
    override fun visitConditionalEffectDeclaration(
        conditionalEffect: KtConditionalEffectDeclaration<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding {
        val effect = conditionalEffect.effect.accept(this, data)
        val cond = conditionalEffect.condition.accept(this, data)
        // The effect's source role it is guaranteed to be not null. The same goes for the condition's source role.
        val role = SourceRole.ConditionalEffect(
            effect.sourceRole as SourceRole.ReturnsEffect,
            cond.sourceRole as SourceRole.Condition
        )
        return OperatorExpEmbeddings.Implies(effect, cond, role)
    }

    /**
     * Converts a `callsInPlace(lambda, ...)` effect declaration.
     * This effect has no Viper representation; it is mapped to `true` (trivially satisfied)
     * so that functions using `callsInPlace` can still be processed without error.
     */
    override fun visitCallsEffectDeclaration(
        callsEffect: KtCallsEffectDeclaration<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding {
        return BooleanLit(true)
    }

    /**
     * Converts an `x is T` or `x !is T` predicate in a contract condition into an [Is] check.
     * The argument variable is resolved via [embeddedVar]; the target type is embedded via
     * the program context. Negated predicates are wrapped in [OperatorExpEmbeddings.Not].
     */
    override fun visitIsInstancePredicate(
        isInstancePredicate: KtIsInstancePredicate<ConeKotlinType, ConeDiagnostic>,
        data: ContractVisitorContext,
    ): ExpEmbedding {
        val argVar = isInstancePredicate.arg.embeddedVar()
        val argSymbol = isInstancePredicate.arg.getTargetParameter(data)
        val role = SourceRole.Condition.IsType(argSymbol, isInstancePredicate.type, isInstancePredicate.isNegated)
        return if (isInstancePredicate.isNegated) {
            OperatorExpEmbeddings.Not(Is(argVar, ctx.embedType(isInstancePredicate.type)), role)
        } else {
            Is(argVar, ctx.embedType(isInstancePredicate.type), role)
        }
    }

    /**
     * According to the input index, invoke `default` if the index is equal to -1, otherwise
     * invoke `mapper` with the given index as input.
     *
     * Index -1 is the convention used by the contract description AST to refer to the
     * dispatch/extension receiver rather than a numbered value parameter. [default] is
     * evaluated lazily (via inlining) to avoid NPEs when the index is not -1.
     */
    private inline fun <T> resolveByIndex(index: Int, default: () -> T, mapper: (Int) -> T): T {
        // Implementation notes: the `default` value is lazily evaluated, since
        // we could get a possible NPE if the index is different from -1.
        // Thanks to inlining, we do not create any extra objects when invoking the function.
        return when (index) {
            -1 -> default()
            else -> mapper(index)
        }
    }

    /**
     * Resolves this parameter reference to its [VariableEmbedding] in the function signature,
     * using [parameterIndex] to identify the formal parameter (-1 = receiver, ≥0 = value param).
     */
    private fun KtValueParameterReference<ConeKotlinType, ConeDiagnostic>.embeddedVar(): VariableEmbedding =
        embeddedVarByIndex(parameterIndex)

    /**
     * Resolves this parameter reference to the underlying [FirBasedSymbol] for use in
     * [SourceRole] metadata. Index -1 returns the function symbol itself (i.e. the receiver
     * owner); index ≥0 returns the corresponding value parameter symbol.
     */
    private fun KtValueParameterReference<ConeKotlinType, ConeDiagnostic>.getTargetParameter(data: ContractVisitorContext): FirBasedSymbol<*> =
        resolveByIndex(
            parameterIndex,
            { data.functionContractOwner }) { data.functionContractOwner.valueParameterSymbols[it] }

    /**
     * Returns the receiver that is valid for use inside contracts.
     * If both an extension receiver and a dispatch receiver are present, only the extension
     * receiver may be referenced in contracts (Kotlin's contract language restriction).
     */
    // If both receivers are present only references to extension receivers will be allowed in contract.
    private fun allowedReceiver() = signature.extensionReceiver ?: signature.dispatchReceiver

    /**
     * Looks up the [VariableEmbedding] for a formal parameter by its index:
     * - Index -1 → the allowed receiver (extension or dispatch).
     * - Index ≥0 → the value parameter at that position in the signature.
     */
    private fun embeddedVarByIndex(ix: Int): VariableEmbedding =
        resolveByIndex(ix, { allowedReceiver()!! }) { signature.params[it] }

    /**
     * Generates a null comparison expression for this variable.
     * - `isNegated = false` → `variable == null` ([EqCmp])
     * - `isNegated = true`  → `variable != null` ([NeCmp])
     */
    private fun VariableEmbedding.nullCmp(isNegated: Boolean, sourceRole: SourceRole?): ExpEmbedding =
        if (isNegated) NeCmp(this, NullLit, sourceRole)
        else EqCmp(this, NullLit, sourceRole)
}
