

package org.jetbrains.kotlin.formver.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.formver.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("formver.compiler-plugin/locality/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class LocalityDiagnosticTestGenerated extends AbstractLocalityDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/locality/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("assign_local.kt")
  public void testAssign_local() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/assign_local.kt");
  }

  @Test
  @TestMetadata("assign_property.kt")
  public void testAssign_property() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/assign_property.kt");
  }

  @Test
  @TestMetadata("call.kt")
  public void testCall() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/call.kt");
  }

  @Test
  @TestMetadata("call_with_context.kt")
  public void testCall_with_context() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/call_with_context.kt");
  }

  @Test
  @TestMetadata("call_with_vararg.kt")
  public void testCall_with_vararg() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/call_with_vararg.kt");
  }

  @Test
  @TestMetadata("default_argument.kt")
  public void testDefault_argument() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/default_argument.kt");
  }

  @Test
  @TestMetadata("invalid.kt")
  public void testInvalid() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/invalid.kt");
  }

  @Test
  @TestMetadata("nested_scope.kt")
  public void testNested_scope() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/nested_scope.kt");
  }

  @Test
  @TestMetadata("return.kt")
  public void testReturn() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/return.kt");
  }

  @Test
  @TestMetadata("throw.kt")
  public void testThrow() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/throw.kt");
  }
}
